repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.6"]
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.3.2
    hooks:
      - id: pytest
        args: ["-q", "tests/unit"]
