general:
  seed: 42
  run_name: ttlab-smoke
paths:
  data_raw: data/raw
  data_processed: data/processed
  data_splits: data/splits
  out_metrics: out/metrics
  out_artifacts: out/artifacts
data:
  format: JSONL
  input_path: tests/resources/sample.jsonl
  schema_fields:
    - field_name: id
      type: int
      required: true
    - field_name: text
      type: str
      required: true
    - field_name: label
      type: str
      required: true
mlflow:
  tracking_uri: file:./mlruns
  experiment: ttlab-A1
  artifact_location: null
