trainer:
  batch_size: 64
  lr: 0.0003
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps: 100
  max_steps: 400
  grad_clip: 1.0
  grad_ckpt: false
  log_interval: 20
  eval_interval: 100
  num_workers: 0
  device: auto
