trainer:
  batch_size: 8
  lr: 0.0003
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps: 200
  max_steps: 2000
  grad_clip: 1.0
  grad_ckpt: false
  log_interval: 50
  eval_interval: 200
  num_workers: 0
  device: auto
